Invalid NNF header
ERROR: load a graph first
ERROR: load a graph first
Traceback (most recent call last):
  File "../tools/query_wrapper.py", line 50, in <module>
    print("ANSWER:", float(output.decode('utf-8').split()[-1]))
ValueError: could not convert string to float: '>'
Command exited with non-zero status 1
	Command being timed: "python ../tools/query_wrapper.py -m 32 d4 data/mc2022_track2_189.cnf.minic2d.cnf"
	User time (seconds): 3589.96
	System time (seconds): 1.60
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:00:00
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1339868
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 753042
	Voluntary context switches: 232
	Involuntary context switches: 5004
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
